- alias: Double Click to toggle Peter nightstand
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001870d6f
      click_type: double
  action:
    service: light.toggle
    data:
      entity_id: light.nattbord_peter

- alias: Single Click to toggle Peter nightstand
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001870d6f
      click_type: single
  action:
    service: light.toggle
    data:
      entity_id: light.nattbord_natalia

- alias: Long Press to toggle bedroom lights
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001870d6f
      click_type: long_click_press
  action:
    service: light.toggle
    data:
      entity_id: light.soverom_2